baseURL = 'https://idontlikeads.com/'
languageCode = 'en-gb'
title = "I Don't Like Ads"
enableRobotsTXT = true
enableEmoji = true
disableKinds = ["taxonomy", "term"]

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[params]
    description = "I don't like ads. You don't like ads. Please stop."
    github_url = "https://github.com/LyleDavis/idontlikeads.com"

